const fs = require('fs');
const lines = [];
lines.push(\"const path = require('path');\");
lines.push(\"require('dotenv').config({ path: path.join(__dirname, '../.env') });\");
lines.push(\"\");
lines.push(\"const express = require('express');\");
lines.push(\"const cors = require('cors');\");
lines.push(\"const mongoose = require('mongoose');\");
lines.push(\"\");
lines.push(\"const menuData = require('./menu-data');\");
lines.push(\"const Order = require('./models/Order');\");
lines.push(\"\");
lines.push(\"const app = express();\");
lines.push(\"const PORT = process.env.PORT ? process.env.PORT : 3000;\");
lines.push(\"\");
lines.push(\"app.use(cors());\");
lines.push(\"app.use(express.json());\");
lines.push(\"app.use(express.urlencoded({ extended: true }));\");
lines.push(\"\");
lines.push(\"app.get('/api/menu', function (req, res) {\");
lines.push(\"    res.json({ success: true, data: menuData });\");
lines.push(\"\");
lines.push(\"app.post('/api/orders', async function (req, res) {\");
lines.push(\"    try {\");
lines.push(\"        const orderId = req.body.orderId;\");
lines.push(\"        const customerName = req.body.customerName;\");
lines.push(\"        const customerEmail = req.body.customerEmail;\");
lines.push(\"        const customerPhone = req.body.customerPhone;\");
lines.push(\"        const customerPincode = req.body.customerPincode;\");
lines.push(\"        const customerAddress = req.body.customerAddress;\");
lines.push(\"        const customerLandmark = req.body.customerLandmark;\");
lines.push(\"        const orderItems = req.body.orderItems;\");
lines.push(\"        const totalAmount = req.body.totalAmount;\");
lines.push(\"        const status = req.body.status ? req.body.status : 'confirmed';\");
lines.push(\"\");
lines.push(\"        if (!orderId) { return res.status(400).json({ success: false, message: 'Missing required fields' }); }\");
lines.push(\"        if (!customerName) { return res.status(400).json({ success: false, message: 'Missing required fields' }); }\");
lines.push(\"        if (!orderItems) { return res.status(400).json({ success: false, message: 'Missing required fields' }); }\");
lines.push(\"        if (!totalAmount) { return res.status(400).json({ success: false, message: 'Missing required fields' }); }\");
lines.push(\"\");
lines.push(\"        const createdOrder = await Order.create({\");
lines.push(\"            order_id: orderId,\");
lines.push(\"            customer_name: customerName,\");
lines.push(\"            customer_email: customerEmail,\");
lines.push(\"            customer_phone: customerPhone,\");
lines.push(\"            customer_pincode: customerPincode,\");
lines.push(\"            customer_address: customerAddress,\");
lines.push(\"            customer_landmark: customerLandmark,\");
lines.push(\"            order_items: orderItems,\");
lines.push(\"            total_amount: totalAmount,\");
lines.push(\"            status: status\");
lines.push(\"        });\");
lines.push(\"\");
lines.push(\"        console.log('==============================');\");
lines.push(\"        console.log('NEW ORDER RECEIVED');\");
lines.push(\"        console.log('Order ID: ' + createdOrder.order_id);\");
lines.push(\"        console.log('Customer: ' + createdOrder.customer_name);\");
lines.push(\"        console.log('Total Amount: ' + createdOrder.total_amount);\");
lines.push(\"        console.log('Timestamp: ' + new Date().toISOString());\");
lines.push(\"        console.log('Order saved to MongoDB successfully');\");
lines.push(\"        console.log('==============================');\");
lines.push(\"\");
lines.push(\"        return res.status(201).json({ success: true, message: 'Order saved successfully', data: [createdOrder] });\");
lines.push(\"    } catch (error) {\");
lines.push(\"        if (error.code === 11000) { return res.status(409).json({ success: false, message: 'Order ID already exists' }); }\");
lines.push(\"        console.error('==============================');\");
lines.push(\"        console.error('FAILED TO SAVE ORDER');\");
lines.push(\"        console.error('Error: ' + error.message);\");
lines.push(\"        console.error('Time: ' + new Date().toISOString());\");
lines.push(\"        console.error('==============================');\");
lines.push(\"        return res.status(500).json({ success: false, message: 'Failed to save order' });\");
lines.push(\"    }\");
lines.push(\"\");
lines.push(\"app.get('/api/orders', async function (req, res) {\");
lines.push(\"    try {\");
lines.push(\"        const orders = await Order.find({}).sort({ created_at: -1 });\");
lines.push(\"        console.log('Admin requested orders list');\");
lines.push(\"        console.log('Orders returned: ' + orders.length);\");
lines.push(\"        console.log('Timestamp: ' + new Date().toISOString());\");
lines.push(\"        return res.json({ success: true, data: orders });\");
lines.push(\"    } catch (error) {\");
lines.push(\"        console.error('MongoDB error:', error.message);\");
lines.push(\"        return res.status(500).json({ success: false, message: 'Failed to fetch orders' });\");
lines.push(\"    }\");
lines.push(\"});\");
lines.push(\"\");
lines.push(\"app.put('/api/orders/:orderId', async function (req, res) {\");
lines.push(\"    try {\");
lines.push(\"        const orderId = req.params.orderId;\");
lines.push(\"        const status = req.body.status;\");
lines.push(\"        if (!status) { return res.status(400).json({ success: false, message: 'Status is required' }); }\");
lines.push(\"        const updatedOrder = await Order.findOneAndUpdate({ order_id: orderId }, { status: status }, { new: true });\");
lines.push(\"        if (!updatedOrder) { return res.status(404).json({ success: false, message: 'Order not found' }); }\");
lines.push(\"        return res.json({ success: true, message: 'Order updated successfully', data: [updatedOrder] });\");
lines.push(\"    } catch (error) {\");
lines.push(\"        console.error('MongoDB error:', error.message);\");
lines.push(\"        return res.status(500).json({ success: false, message: 'Failed to update order' });\");
lines.push(\"    }\");
lines.push(\"});\");
lines.push(\"\");
lines.push(\"app.delete('/api/orders/:orderId', async function (req, res) {\");
lines.push(\"    try {\");
lines.push(\"        const orderId = req.params.orderId;\");
lines.push(\"        const deletedOrder = await Order.findOneAndDelete({ order_id: orderId });\");
lines.push(\"        if (!deletedOrder) { return res.status(404).json({ success: false, message: 'Order not found' }); }\");
lines.push(\"        return res.json({ success: true, message: 'Order deleted successfully' });\");
lines.push(\"    } catch (error) {\");
lines.push(\"        console.error('MongoDB error:', error.message);\");
lines.push(\"        return res.status(500).json({ success: false, message: 'Failed to delete order' });\");
lines.push(\"    }\");
lines.push(\"});\");
lines.push(\"\");
lines.push(\"app.post('/contact', function (req, res) {\");
lines.push(\"    const name = req.body.name;\");
lines.push(\"    const email = req.body.email;\");
lines.push(\"    const message = req.body.message;\");
lines.push(\"    if (!name) { return res.status(400).json({ success: false, message: 'All fields are required' }); }\");
lines.push(\"    if (!email) { return res.status(400).json({ success: false, message: 'All fields are required' }); }\");
lines.push(\"    if (!message) { return res.status(400).json({ success: false, message: 'All fields are required' }); }\");
lines.push(\"    console.log('Contact form message from ' + name + ' (' + email + '): ' + message);\");
lines.push(\"    return res.json({ success: true, message: 'Message received successfully! We will get back to you soon.' });\");
lines.push(\"});\");
lines.push(\"\");
lines.push(\"app.get('/health', function (req, res) {\");
lines.push(\"    return res.json({ status: 'OK', timestamp: new Date().toISOString() });\");
lines.push(\"});\");
lines.push(\"\");
lines.push(\"app.use(express.static(path.join(__dirname, '../public')));\");
lines.push(\"app.get('/', function (req, res) { res.sendFile(path.join(__dirname, '../public', 'index.html')); });\");
lines.push(\"\");
lines.push(\"mongoose.connection.on('connected', function () {\");
lines.push(\"    console.log('Database state: connected');\");
lines.push(\"});\");
lines.push(\"mongoose.connection.on('disconnected', function () {\");
lines.push(\"    console.warn('Database state: disconnected');\");
lines.push(\"});\");
lines.push(\"mongoose.connection.on('reconnected', function () {\");
lines.push(\"    console.log('Database state: reconnected');\");
lines.push(\"});\");
lines.push(\"mongoose.connection.on('error', function (error) {\");
lines.push(\"    const errorMessage = error ? (error.message ? error.message : error) : error;\");
lines.push(\"    console.error('Database state: error - ' + errorMessage);\");
lines.push(\"});\");
lines.push(\"\");
lines.push(\"async function connectMongo() {\");
lines.push(\"    if (!process.env.MONGODB_URI) {\");
lines.push(\"        console.error('\\u274C MONGODB_URI not found in .env');\");
lines.push(\"        process.exit(1);\");
lines.push(\"    }\");
lines.push(\"    console.log('\\uD83D\\uDFE1 Connecting to MongoDB...');\");
lines.push(\"    try {\");
lines.push(\"        await mongoose.connect(process.env.MONGODB_URI);\");
lines.push(\"        console.log('MongoDB Connected Successfully');\");
lines.push(\"        console.log('Database Host: ' + mongoose.connection.host);\");
lines.push(\"        console.log('Database Name: ' + mongoose.connection.name);\");
lines.push(\"        console.log('Connection Time: ' + new Date().toISOString());\");
lines.push(\"        console.log('\\uD83D\\uDCE6 Database connection established');\");
lines.push(\"        app.listen(PORT, function () {\");
lines.push(\"            console.log('\\uD83D\\uDE80 Server running on http://localhost:' + PORT);\");
lines.push(\"        });\");
lines.push(\"    } catch (error) {\");
lines.push(\"        console.error('\\uD83D\\uDD34 MongoDB connection failed');\");
lines.push(\"        console.error(error.message);\");
lines.push(\"        process.exit(1);\");
lines.push(\"    }\");
lines.push(\"}\");
lines.push(\"\");
lines.push(\"connectMongo();\");
lines.push(\"\");
lines.push(\"module.exports = app;\");
fs.writeFileSync('backend/server.js', lines.join('\n'));
